### ISSUE TITLE
建議深色主題鍵盤鍵帽配色用半透明白色

### ISSUE THREAD

**Issue by hakadao** [yuetyam/jyutping#1]
第一張相係粵拼鍵盤，第二個係系統鍵盤
系統嗰個鍵盤喺白色背景情況下都係可以清晰噉顯示鍵帽出嚟。仲有系統內置嘅鍵盤喺淺色主題嗰陣鍵帽都係半透明嘅
![98E37FE0-F146-4F60-ADAC-060BADFEE692.jpeg](https://i.loli.net/2021/01/22/QXjerNAdZ7pFmtJ.jpg)
![E1677FFD-2E19-42F7-A8DF-6B5CA33EDFBE.jpeg](https://i.loli.net/2021/01/22/WDixIrpo7ltg5d1.jpg)

**Comment by bingzheung** [comment]
Hi! @hakadao 

首先多謝你嘅建議！

我呢幾日唔得閒，要遲啲再睇睇。

有進展我會再來回復下嘅

**Comment by bingzheung** [comment]
Hi @hakadao 

我做咗小小改進 #https://github.com/yuetyam/jyutping/commit/87b633196fdfb3c59f047875cbcd24fb3f975c95 ，而家深色鍵盤有咗少少透明嘞，白色鍵盤暫時仲係噉。下次 App Store 更新睇睇效果。

我會繼續改善呢個問題嘅，多謝你嘅建議！
