### ISSUE TITLE
候選詞遮擋或顯示不全

### ISSUE THREAD

**Issue by ryj5566** [yuetyam/jyutping#11]
在Safari地址欄進行輸入時，時不時會發生候選詞被遮擋的問題。（有時會僅出來第一條候選，有時一條也不顯示）
<img width="714" alt="1" src="https://user-images.githubusercontent.com/51884639/170850951-673f6142-c65c-4853-89c4-99edf3ad74e4.png">

**Comment by bingzheung** [comment]
Hi @ryj5566 

唔該晒反饋回報。呢個問題唔單止 Safari 會有，我會嘗試修復嘅嘞。

**Comment by bingzheung** [comment]
暫時解決辦法：出現呢種情況之後，切換到其他輸入法，再切換返來粵拼，一般會好返。

**Comment by bingzheung** [comment]
Hi @ryj5566 

新版(v0.18.0)釋出啦，試下睇睇修復咗未。

**Comment by bingzheung** [comment]
我自己體驗，v0.18.0 依然有呢個問題。

同樣遇到嘅朋友，可以喺 Terminal 執行：
```
osascript -e 'tell application id "org.jyutping.inputmethod.Jyutping" to if it is running then quit'
```
就會暫時好返。

**Comment by ryj5566** [comment]
多謝解答

**Comment by bingzheung** [comment]
Hi @ryj5566 

我出咗個新版 v0.19.0
今次應該修復咗啦
