### ISSUE TITLE
macOS 13.0 Beta2 安装程序后无法添加输入法

### ISSUE THREAD

**Issue by makhocheung** [yuetyam/jyutping#12]
请问如何卸载程序

**Comment by bingzheung** [comment]
Hi @makhocheung 


安裝之後如果見唔到有粵拼輸入法，請前往 系統偏好設定 → 鍵盤 → 輸入方式 度添加。
添加箇陣，「粵拼」位於 Cantonese/粵語/廣東話 語言項，亦可以用 粵拼/粤拼/jyutping 來搜索搵到。


如果要卸載粵拼輸入法，刪除 `~/Library/Input Methods/Jyutping.app` 即可。


另外，喺 macOS 安裝或者卸載輸入法之後，需要登出電腦再登入，或者重啓一下電腦。

**Comment by makhocheung** [comment]
macOS 12.4 冇问题嘅，估计系新版本系统兼容问题。

**Comment by makhocheung** [comment]
Beta 3 冇呢个问题嘞
