### ISSUE TITLE
可否導出用户字典？

### ISSUE THREAD

**Issue by JacoChong** [yuetyam/jyutping#13]
想將個人用户字典導出作研究同頻序表用途

**Comment by bingzheung** [comment]
Hi @JacoChong 

暫時冇提供呢個功能，以後會考慮做。

如果你用緊 Mac 版，佢個用戶詞庫位於 `~/Library/Containers/org.jyutping.inputmethod.Jyutping/Data/Library/userlexicon.sqlite3` ，用常見嘅 SQLite 程式應該唔難打開。

iOS 版位置亦相似，不過比較難訪問到。

鍵盤用戶詞庫嘅相關程式碼喺
https://github.com/yuetyam/jyutping/blob/master/Jyutping/IOSKeyboard/UserLexicon.swift

**Comment by JacoChong** [comment]
@ososoio 好嘅唔該晒
