### ISSUE TITLE
使用粤拼键盘进行听写时出现问题

### ISSUE THREAD

**Issue by koinsj** [yuetyam/jyutping#15]
手机系统是iOS 16.0，我也不清楚是iOS本身的问题还是app的问题。我在app的0.17.0与0.20.0版本都遇见过这个问题，我觉得可能有关联，就一并贴出来了。

0.17.0版本：使用粤拼键盘进行听写时，切换听写语言导致键盘一并切换。
https://user-images.githubusercontent.com/104575691/191740199-83fc50fe-ddfc-4cab-9906-275adcfe236a.MOV

另外，即使在使用粤拼键盘时切换好了听写语言，在切换到iOS 英语键盘并进行英语听写后，再切换回粤拼键盘进行听写，听写语言仍旧保持为英语，这时再切换听写语言就又会重复第一个问题。
https://user-images.githubusercontent.com/104575691/191746116-0abbcf3f-3166-44ac-bc70-ffe044ee950e.MOV

0.20.0版本：使用粤拼键盘时，轻点听写按钮完全无法进入听写状态（在粤拼app内的输入框进行这个尝试时还有可能导致app闪退），长按选择听写语言可以进入听写状态，但也会导致键盘同时切换。
https://user-images.githubusercontent.com/104575691/191748601-6485423b-95d0-4403-a349-61b38de319b1.MOV

**Comment by bingzheung** [comment]
Hi @koinsj 

呢個係 iOS 嘅問題。

版本 v0.17.0 嘅現象，係因爲我將鍵盤嘅首要語言設定成咗 `mul`，即係多種語言，冇指定邊一種。所以切換到某種語言聽寫之後，iOS 會選擇切換到同聽寫語言相同嘅嗰隻鍵盤。

版本 v0.20.0 嘅現象，係因爲我將鍵盤嘅首要語言換成咗 `yue`，即係粵語。啓用呢個鍵盤之後，iOS 會喺聽寫語言列表嗰度添加一個「繁體廣東話 / Cantonese, Traditional」。而 iOS 本身並冇呢個聽寫語言，所以輕點聽寫掣之後，會即刻閃退。

暫時解決辦法，你去 系統設定App -> 一般 -> 鍵盤 -> 聽寫語言 嗰度，將「繁體廣東話 / Cantonese, Traditional」取消勾選。

我會喺後續版本將鍵盤嘅首要語言換成 `zh-HK`，應該就可以規避呢個問題嘞。

**Comment by koinsj** [comment]
多谢，取消勾选之后可以进行听写啦，就系键盘无对应听写语言仲有小小麻烦。

不过我仲有一个小疑问，未来更新之后会唔会同时支持简体粤语同繁体粤语嘅听写呢。就好似而家IOS嘅简体拼音键盘可以喺“普通话”同“粤语 - 中国大陆”之间切换都无问题咁。

再次多谢解答。

**Comment by bingzheung** [comment]
@koinsj 

> 不过我仲有一个小疑问，未来更新之后会唔会同时支持简体粤语同繁体粤语嘅听写呢。就好似而家IOS嘅简体拼音键盘可以喺“普通话”同“粤语 - 中国大陆”之间切换都无问题咁。

我認爲冇辦法做到。呢個問題係 iOS 自己控制嘅，我哋做唔到乜嘢。佢系統鍵盤可以噉，可能係因爲佢哋有特權啩。

**Comment by koinsj** [comment]
多谢回复！

其实我之所以会咁问，系因为我之前用过一阵搜狗输入法，喺`上海话`、`普通话`同`粤语 - 中国大陆`呢三种听写语言之间切换嘅时候并唔会导致键盘之间嘅切换。

不过我刚刚重新下载返嚟试咗下，如果想喺`粤语 - 中国大陆`同`廣東話 - 香港`之间切换，依然会导致跳转到另一个键盘(之后喺iOS自带键盘亦得到咗同样嘅结果)。

咁样睇落，其实苹果可能只不过将`上海话`、`普通话`同`粤语 - 中国大陆`全部归入咗简体中文，我已经放弃希望🤣。

既然无法同时照顾，你就按照你嘅喜好嚟做啦。

**Comment by bingzheung** [comment]
@koinsj 

多謝提供咁多信息

**Comment by bingzheung** [comment]
Hi @koinsj 

新版（v0.21.0）應該修復呢個問題喇。
