### ISSUE TITLE
粵拼轉中文字

### ISSUE THREAD

**Issue by Keith-Hon** [yuetyam/jyutping#17]
![78cca9bd-c571-4687-bfc3-3772401beaf9](https://user-images.githubusercontent.com/23226987/231724490-bd76e3a0-76d3-4bcb-bf7b-253ee099c440.jpg)

Apple's
![056dc0ec-522e-4acc-a652-5663d18d0134](https://user-images.githubusercontent.com/23226987/231724634-edee5fa5-7451-492e-85ad-f355930c53de.jpg)

**Comment by bingzheung** [comment]
Hi @Keith-Hon 

多謝分享。目前個組詞造句能力的確有待加強。我會繼續改進嘅喇。

**Comment by Keith-Hon** [comment]
想請教一下 目前組詞造句係點樣做嫁?

**Comment by bingzheung** [comment]
目前只係將啲高頻字詞進行組合，來匹配拼音。冇任何語義相關嘅嘢，所以往往唔成句。

我一直想用 n-gram 語言模型來改善組句能力，弊在遲遲冇時間整。

**Comment by Keith-Hon** [comment]
而家點知個詞係唔係高頻同幾高頻?

**Comment by bingzheung** [comment]
https://github.com/rime/rime-cantonese 呢度有個 essay-cantonese.txt 有詞頻。

**Comment by Keith-Hon** [comment]
ok thanks!, 而家 https://github.com/yuetyam/jyutping 邊個file處理組詞造句呢部分logic?

**Comment by bingzheung** [comment]
> 而家邊個file處理組詞造句呢部分logic?

比較複雜……

**Comment by Keith-Hon** [comment]
LOL...

**Comment by Keith-Hon** [comment]
可以簡單咁講下個logic嗎?
