### ISSUE TITLE
macos版本是否可以支持簡體中文顯示

### ISSUE THREAD

**Issue by ColinWorld** [yuetyam/jyutping#18]
而家通過粵拼輸入法出來嘅喺繁體中文，macos端是否可以支持簡體中文

**Comment by bingzheung** [comment]
Hi @ColinWorld 

撳 `Control` + `Shift` + `` ` `` 會顯示一個選單，跟住就可以揀字形啦。（`` ` `` 係 `esc` 下邊箇粒掣。）

<img width="275" alt="switches" src="https://user-images.githubusercontent.com/44096493/232757009-616bdbb4-a45d-42a0-94c2-e48780bad7d0.png">

**Comment by ColinWorld** [comment]
> 
多谢嗮
