### ISSUE TITLE
Development environment question 

### ISSUE THREAD

**Issue by aiongg** [yuetyam/jyutping#19]
Hello, I hope you don't mind me asking here. I am working on a cross-platform Taiwanese IME. I am struggling to set up a reasonable development environment for Mac OSX. Do you have some ways to develop the app without logging out and logging in every time to use the new build? Do you have any way to debug the IME besides simple text logging? I've looked through your repo a bit but I did not find any solutions, so I thought I would ask.

Thanks

**Comment by bingzheung** [comment]
Hi @aiongg 

You may want to have a look at this article: https://www.logcg.com/archives/2078.html

**Comment by aiongg** [comment]
Thank you, I already saw that article, but for me it seems I am unable to rebuild and use the new code without logging out and logging in again. Also, the article mentions that it's not possible to debug, so I guess this is correct?

**Comment by bingzheung** [comment]
I guess there's no way to use Xcode to debug the IME, logging is the only way.

About the rebuild issue, I think killing the old IME running instance before replacing it may help, not sure.

As an example, here is the command line to quit the Jyutping IME:
~~~bash
osascript -e 'tell application id "org.jyutping.inputmethod.Jyutping" to quit'
~~~

**Comment by aiongg** [comment]
That was my missing step. Seems like a simple `killall -9` works just fine. Great, well at least with file logging and being able to reload without logging out, I can actually do some work. Thanks for the tip!
