### ISSUE TITLE
可否把輸入方法設定放在系統的預設位置

### ISSUE THREAD

**Issue by JordanQD** [yuetyam/jyutping#22]
![CleanShot 2023-12-16 at 14 06 19@2x](https://github.com/yuetyam/jyutping/assets/25655766/97359e8c-6d16-4f6a-82d3-d6abb789ef10)
就係呢度

**Comment by bingzheung** [comment]
Hi @JordanQD 

多謝建議。
系統 設定App 相對局限，有可能有某啲設定項支援唔到，例如設定候選詞字體等。
輸入法自己嘅設定窗口更加靈活，以後可能仲會喺設定嗰度加入各種示意圖等等。
所以我都係唔打算使用系統設定App嘞。
