### ISSUE TITLE
[Bug] 輸入法喺mac機嘅Spotlight Search下底

### ISSUE THREAD

**Issue by hakadao** [yuetyam/jyutping#23]
https://github.com/yuetyam/jyutping/assets/33394391/2ae6fd25-f708-4a02-a3b8-7928f14f19dd

**Comment by bingzheung** [comment]
Hi @hakadao 

唔該晒提醒，我會試下修復。

**Comment by bingzheung** [comment]
下次更新應該會好返嘞。
