### ISSUE TITLE
Support for external keyboards

### ISSUE THREAD

**Issue by owen-hwlee** [yuetyam/jyutping#5]
I'm not sure if this is actually available in current versions of iOS, but I would really love it if the app can support external bluetooth keyboards.
There is a chance, however, that this could be prohibited or limited by iOS, due to me not being able to properly use Kaiboard with the wireless keyboard as well.
If this is the case, thank you for your time.

**Comment by bingzheung** [comment]
Hi @owen-hwlee 

There's no way to use external keyboards with third-party keyboard apps, even on iPadOS 15.
It's all up to Apple, nothing we can do.

Thank you for your concern.
